<!DOCTYPE html>
<html>

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>meu primeiro Crud</title>
    <link rel="stylesheet" href="<?= DIR_BOOTSTRAP_CSS ?>bootstrap.css">
    <link href="https://fonts.googleapis.com/css?family=Baskervville|Caveat|Fredoka+One|Inconsolata|Lobster|Montserrat|Source+Code+Pro&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="<?= DIRCSS ?>global.css">
    <link rel="stylesheet" href="<?= DIRCSS ?>jquery-confirm.css">
</head>

<body>
    <div id="inicio">
        <div class="bg-dark text-light p-3 d-flex align-items-center" id="cabecalho" style="height:14vh;">
            <h3>Bem Vindo!</h3>
        </div>
        <div class="corpo my-1">
