<div class="container my-3">
    <div class="mx-auto col-6 d-flex align-items-center justify-content-center" id="projetos">
        <h1 class="text-center mr-4">Meus Projetos</h1>
        <a href="/crud/Projetos/main">
            <i class="fas fa-folder-plus text-success font-size-25 pointer"></i>
        </a>
    </div>

    <div class="list-group" id="listagem">

    </div>
</div>

<!-- FECHAMENTO TAG CORPO -->
</div>
<!-- FECHAMENTO TAG CORPO -->
