<div class="container">
    <div class="col-5 mx-auto py-5">
        <p id="titulo">Faça o <span>login</span> para continuar!</p>
        <form class="needs-validation">
            <div class="form-group">

                <div class="my-3 text-secondary">
                    <label for="github">Seu nome do Git!</label>
                    <input id="github" type="text" name="githubUsername" placeholder="coloque seu nome do Github!" class="form-control" autocomplete="off" required>
                </div>
                <div class="my-3 text-secondary">
                    <label for="senha">Senha</label>
                    <input id="senha" type="password" name="password" placeholder="Digite sua senha aqui" class="form-control" autocomplete="off" required>
                </div>
                <div id="cadastrar" style="display:none;">
                    <div class="password text-secondary">
                        <label for="senhaConf">Confirme sua Senha</label>
                        <input id="senhaConf" name="senhaConf" type="password" placeholder="Digite sua senha aqui" class="form-control" autocomplete="off">
                        <span class="text-danger font-size-13 d-none font-weight-bold">*As senhas devem ser iguais!</span>
                    </div>
                    <div class="my-3 text-secondary">
                        <label for="usuario">E-mail</label>
                        <input id="usuario" type="text" name="email" placeholder="seuemailaqui@exemplo.com.br" class="form-control">
                    </div>
                    <div class="d-flex justify-content-between my-3 text-secondary">
                        <div class="idade col pr-2 pl-0">
                            <label for="dtNasc">Data de nascimento</label>
                            <input id="dtNasc" type="date" name="dtNasc" class="form-control">
                        </div>
                        <div class="sexo col px-0 text-secondary form-select">
                            <label for="sexo">Sexo</label>
                            <select class="form-control custom-select" name="genero" id="sexo">
                                <option value="">Selecione uma opção</option>
                                <option value="M">Masculino</option>
                                <option value="F">Feminino</option>
                            </select>
                        </div>
                    </div>

                </div>
            </div>
            <div class="my-2 mx-auto" id="divBotoes">
                <span id="esqueceuSenha" class="font-size-13 mx-2 tagA">Esqueceu a senha?</span>
                <div class="font-size-13 text-danger font-weight-bold my-1 d-none dadosInc">*Existem Dados que não foram preenchidos!</div>
            </div>
        </form>
        <div>
            <span id="novoCadastro" class="font-size-13 tagA">Ainda não em um cadastro ? Clique aqui!</span>
        </div>
    </div>
</div>

<!-- FECHAMENTO DA DIV CORPO -->
</div>
<!-- FECHAMENTO DA DIV CORPO -->
